### ISSUE TITLE
Command doesn't appear on Mobile

### ISSUE THREAD

**Issue by Zapidipodot** [DeltaNedas/dev-mode#20] opened 2022-10-14 11:00 UTC
I have downloaded or imported the ui-lib and dev-mode on my phone and the command didn't appear. i tried it on bleeding edge, 137, and 139 and still not there. how to fix this?

**Comment by deltanedas** [comment] 2022-10-27 22:28
duplicate of #19

**Closed as completed by deltanedas** 2022-10-27 22:28 UTC
